#!/bin/bash
git pull


# cd web-vite && npm run lint
# if [ "$?" != 0 ]; then 
#   echo "Erro no lint web"
#   exit 
# fi
# cd ..


bun lint 

if [ "$?" != 0 ]; then 
  echo "Erro no lint"
  exit 
fi

# bun test

# if [ "$?" != 0 ]; then 
#   echo "Erro nos tests"
#   exit 
# fi



git add .
git commit -m "$1"
git push 

sleep 1

