services:
  postgres_db:
    image: postgres:18
    container_name: postgres_db_ideias

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ideias

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: